FIID-291
Finniu-Tech/Finniu-LandingPage pull request #59
Opened 2024-09-09 05:46 UTC by IngridC10

-Fixed calendar component and curve chart component.

2024-09-09 20:49 UTC, harolCalzada requested changes

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/(home)/components/CurveChartComponent.tsx
> +                      tick={{ fill: darkMode ? "#ffffff" : "#0D3A5C" }}
recomiendo poner estos colores ffffff y  0D3A5C como una variable tipo string, en caso cambien en el rediseño sera mas facil encontrar donde cambiar el color

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/(home)/components/CurveChartComponent.tsx
> +                      tick={{ fill: darkMode ? "#ffffff" : "#0D3A5C" }}
lo mismo para aaca y todos los demas

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/calendar/components/CardRentability.tsx
> +              | number
este typing esta raro, por q se le a asignado tantos tipos al date ?

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/calendar/components/CardRentability.tsx
> +            description:
lo mismo para el description, por q se le ha asignado tantos tipos a este campo?

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/myHistory/components/Transaction.tsx
> +                            | string
lo mismo para este tipado

2024-09-09 20:49 UTC, harolCalzada commented on app/(authenticated)/dashboard/myHistory/components/Transaction.tsx
> +                              | string
este tipado lo mismo

2024-09-09 23:11 UTC, IngridC10 commented on app/(authenticated)/dashboard/(home)/components/CurveChartComponent.tsx
> +                      tick={{ fill: darkMode ? "#ffffff" : "#0D3A5C" }}
ok! Acabo de modificarlo.

2024-09-09 23:12 UTC, IngridC10 commented on app/(authenticated)/dashboard/(home)/components/CurveChartComponent.tsx
> +                      tick={{ fill: darkMode ? "#ffffff" : "#0D3A5C" }}
Ok, Acabo de modificarlo.

2024-09-09 23:26 UTC, IngridC10 commented on app/(authenticated)/dashboard/calendar/components/CardRentability.tsx
> +            description:
ok! ya lo corregí

2024-09-10 00:56 UTC, IngridC10 commented on app/(authenticated)/dashboard/myHistory/components/Transaction.tsx
> +                              | string
ok,ya lo cambie!

2024-09-10 00:56 UTC, IngridC10 commented on app/(authenticated)/dashboard/myHistory/components/Transaction.tsx
> +                            | string
ok,ya lo corregí

2024-09-10 01:01 UTC, harolCalzada approved these changes

2024-09-10 01:01 UTC, merged